pull_request_rules:
  - name: automatic merge for Dependabot devDependencies pull requests
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - check-success=azure-devops-mutationreport-publisher
      - title~=^build\(deps-dev\)
    actions:
      merge:
        method: merge
